apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: demo-k8s
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrier.multi-client
      ports:
        - containerPort: 3000
